import Head from "next/head";

type PropsType = {
  [key: string]: any;
};

export default function Success(props: PropsType) {
  return (
    <>
      <Head>
        <title>提交成功</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>提交成功</h1>
        <p>感谢参与问卷调查，我们会尽快处理您的反馈。</p>
      </main>
    </>
  );
}
